/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tiago Lopes (https://sketchfab.com/drobluda)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skate-936e79f2935c4b28a93a88480d8aa44d
Title: Skate
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Board(props) {
  const { nodes, materials } = useGLTF("/skate.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.skate_low_01_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.skate_low_02_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.skate_low_03_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -2.297, 8.905]}
          scale={3.812}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.skate_low_04_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -2.335, 27.217]}
          rotation={[0, 0.196, 0]}
          scale={[6.125, 2.505, 6.125]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/skate.glb");
