/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: artfletch (https://sketchfab.com/artfletch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/finsbury-park-skatepark-ecb0bc49f490428180ffe177328e3238
Title: Finsbury Park Skatepark
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Park(props) {
  const { nodes, materials } = useGLTF("/skatepark.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, -1.293, 1.68]} rotation={[-Math.PI, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.FinsburyParkSkatePark01_Model_4_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.FinsburyParkSkatePark01_Model_4_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.FinsburyParkSkatePark01_Model_4_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.FinsburyParkSkatePark01_Model_4_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.FinsburyParkSkatePark01_Model_4_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.FinsburyParkSkatePark01_Model_4_u1_v1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/skatepark.glb");
