/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tomciomalina (https://sketchfab.com/tomciomalina)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-wheel-2b6ec6619ac34e668b428855a0caf3c5
Title: Sci fi Wheel
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Wheels(props) {
  const { nodes, materials } = useGLTF("/wheel.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 30.188, 0]}
        rotation={[-1.484, -Math.PI / 2, 0]}
        scale={[0.926, 0.936, 0.963]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cylinder002_01_-_Default_0"].geometry}
          material={materials["01_-_Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cylinder002_03_-_Default_0"].geometry}
          material={materials["03_-_Default"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Cylinder001_02_-_Default_0"].geometry}
        material={materials["02_-_Default"]}
        position={[0, 29.553, 0]}
        rotation={[-1.745, -Math.PI / 2, 0]}
      />
    </group>
  );
}

useGLTF.preload("wheel.glb");
